# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_heck_wrappers", use_symbols = TRUE, package_name = "heck")

#' @usage NULL
#' @useDynLib heck, .registration = TRUE
NULL

#' @rdname caseconverter
#' @export
to_kebab_case <- function(x) .Call(wrap__to_kebab_case, x)

#' @rdname caseconverter
#' @export
to_lower_camel_case <- function(x) .Call(wrap__to_lower_camel_case, x)

#' @rdname caseconverter
#' @export
to_upper_camel_case <- function(x) .Call(wrap__to_upper_camel_case, x)

#' @rdname caseconverter
#' @export
to_pascal_case <- function(x) .Call(wrap__to_pascal_case, x)

#' @rdname caseconverter
#' @export
to_snake_case <- function(x) .Call(wrap__to_snake_case, x)

#' @rdname caseconverter
#' @export
to_snek_case <- function(x) .Call(wrap__to_snek_case, x)

#' @rdname caseconverter
#' @export
to_title_case <- function(x) .Call(wrap__to_title_case, x)

#' @rdname caseconverter
#' @export
to_train_case <- function(x) .Call(wrap__to_train_case, x)

#' @rdname caseconverter
#' @export
to_shouty_kebab_case <- function(x) .Call(wrap__to_shouty_kebab_case, x)

#' @rdname caseconverter
#' @export
to_shouty_snake_case <- function(x) .Call(wrap__to_shouty_snake_case, x)


# nolint end
